# Generated by Django 2.1.7 on 2019-03-31 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('send_post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.BooleanField(default=bool),
            preserve_default=False,
        ),
    ]
